In [1]:
import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

/kaggle/input/datasets/nabilatabassummumu/our-dataset/merged_dataset.csv
/kaggle/input/datasets/nabilatabassummumu/batd-dataset/merge_dataset_aust.csv

In [44]:
!pip install --upgrade transformers

Requirement already satisfied: transformers in /usr/local/lib/python3.12/dist-packages (5.5.0)
Requirement already satisfied: huggingface-hub<2.0,>=1.5.0 in /usr/local/lib/python3.12/dist-packages (from transformers) (1.8.0)
Requirement already satisfied: numpy>=1.17 in /usr/local/lib/python3.12/dist-packages (from transformers) (2.0.2)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.12/dist-packages (from transformers) (26.0)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.12/dist-packages (from transformers) (6.0.3)
Requirement already satisfied: regex>=2025.10.22 in /usr/local/lib/python3.12/dist-packages (from transformers) (2025.11.3)
Requirement already satisfied: tokenizers<=0.23.0,>=0.22.0 in /usr/local/lib/python3.12/dist-packages (from transformers) (0.22.2)
Requirement already satisfied: typer in /usr/local/lib/python3.12/dist-packages (from transformers) (0.24.1)
Requirement already satisfied: safetensors>=0.4.3 in /usr/local/lib/python3.12/dist-packages (from transformers) (0.7.0)
Requirement already satisfied: tqdm>=4.27 in /usr/local/lib/python3.12/dist-packages (from transformers) (4.67.3)
Requirement already satisfied: filelock>=3.10.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0,>=1.5.0->transformers) (3.24.3)
Requirement already satisfied: fsspec>=2023.5.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0,>=1.5.0->transformers) (2026.2.0)
Requirement already satisfied: hf-xet<2.0.0,>=1.4.2 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0,>=1.5.0->transformers) (1.4.3)
Requirement already satisfied: httpx<1,>=0.23.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0,>=1.5.0->transformers) (0.28.1)
Requirement already satisfied: typing-extensions>=4.1.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0,>=1.5.0->transformers) (4.15.0)
Requirement already satisfied: click>=8.2.1 in /usr/local/lib/python3.12/dist-packages (from typer->transformers) (8.3.1)
Requirement already satisfied: shellingham>=1.3.0 in /usr/local/lib/python3.12/dist-packages (from typer->transformers) (1.5.4)
Requirement already satisfied: rich>=12.3.0 in /usr/local/lib/python3.12/dist-packages (from typer->transformers) (13.9.4)
Requirement already satisfied: annotated-doc>=0.0.2 in /usr/local/lib/python3.12/dist-packages (from typer->transformers) (0.0.4)
Requirement already satisfied: anyio in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.5.0->transformers) (4.12.1)
Requirement already satisfied: certifi in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.5.0->transformers) (2026.1.4)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.5.0->transformers) (1.0.9)
Requirement already satisfied: idna in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.5.0->transformers) (3.11)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.12/dist-packages (from httpcore==1.*->httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.5.0->transformers) (0.16.0)
Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.12/dist-packages (from rich>=12.3.0->typer->transformers) (4.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.12/dist-packages (from rich>=12.3.0->typer->transformers) (2.19.2)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.12/dist-packages (from markdown-it-py>=2.2.0->rich>=12.3.0->typer->transformers) (0.1.2)

In [26]:
!pip install -q transformers datasets sentencepiece scikit-learn

# import pandas as pd
# import numpy as np
# import torch
# from sklearn.model_selection import train_test_split
# from sklearn.metrics import accuracy_score, f1_score, precision_score, recall_score
# from datasets import Dataset
# from transformers import (
#     AutoTokenizer,
#     AutoModelForSequenceClassification,
#     Trainer,
#     TrainingArguments,
#     DataCollatorWithPadding
# )

import pandas as pd
import torch
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score
from transformers import AutoTokenizer, AutoModelForSequenceClassification, Trainer, DataCollatorWithPadding, TrainingArguments
from datasets import Dataset

In [3]:
os.listdir("/kaggle/input/datasets/nabilatabassummumu/our-dataset")

['merged_dataset.csv']

In [4]:
df = pd.read_csv("/kaggle/input/datasets/nabilatabassummumu/our-dataset/merged_dataset.csv")

# print(df.head())
print(df["category"].value_counts())

category
politics                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   3420
sports                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     2695
international                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              2300
national                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   1359
literature                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 1251
economy                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     861
economics                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   416
education                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    57
bangladesh                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   44
business                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     19
category                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      2
০৮ মার্চ ২০২৬ শুক্রবার দুপুর ১২টা। পেকুয়ার রাজাখালী ইউনিয়নের হাজীরপাড়ার লবণ মাঠে তপ্ত রোদে কাজ করছেন তিন নারী। বুলু আকতার কুয়ো থেকে পানি তুলে ছিটিয়ে দিচ্ছেন মাঠে। ছেমন আরা ও পারভীন মাঠে রামগতি উপজেলার ৫৩টি ইটভাটার মধ্যে অনুমোদন রয়েছে মাত্র দুটির। বাকি ৫১ ইটভাটা চলছে অনুমোদন ছাড়াই।"                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    1
০৯ মার্চ ২০২৬ মুঠোফোনের মাত্র কয়েকটি ট্যাপেই মুক্তি পাবেন কাপড় ধোয়ার ঝামেলা থেকে। অত্যাধুনিক এআই প্রযুক্তির ৯ কেজি ফ্রন্টলোড ওয়াশিং মেশিন বাজারে এনেছে স্যামসাং! অসিদের হেক্সা জয়? নাকি ভারত জিতবে তৃতীয় বিশ্বকাপ? কেন জন্মদিন উদযাপন করছেন না পরীমনি? | Pori Moni | Samakal News ড. রাশেদ চৌধুরী অ্যারিজোনো স্টেট ইউনিভার্সিটির স্কুল অব সাসটেইনেবল ইঞ্জিনিয়ারিং অ্যান্ড বিল্ট এনভায়রনমেন্ট বিভাগের সহযোগী অধ্যাপক। আশু পূর্বাভাস ব্যবস্থা এবং জলবায়ু পরিবর্তনের সঙ্গে অভিযোজন জটিলতা বিষয়ে গবেষণা করছেন... উদ্বোধনের অপেক্ষায় নদীর তলদেশে দেশের প্রথম টানেল। কী থাকছে এই টানেলে? জাপানিরা নীরোগভাবে দীর্ঘদিন বেঁচে থাকেন। দীর্ঘ আয়ুর পেছনে কাজ করছে তাদের নিয়ন্ত্রিত লাইফস্টাইল ও পরিমিত খাদ্যাভ্যাস। চলুন জেনে নেই জাপানিরা কীভাবে অনেকদিন সুস্থভাবে বেঁচে থাকেন? অলংকার থেকে মুদ্রা       1
০৮ মার্চ ২০২৬ সেরা করদাতা হিসেবে ‘করবাহাদুর’ পুরস্কার পেয়েছিলেন চাঁদ ডাইংয়ের কর্ণধার শিল্পপতি জসিম উদ্দিন মাসুম (৫৯)। গত বুধবার নারায়ণগঞ্জের রূপগঞ্জে পলিথিনে মোড়ানো সাত টুকরা লাশের পরিচয় নিশ্চিতের পর নড়েচড়ে বসে আইনশৃঙ্খলা রক্ষাকারী বাহিনী। সেটি মাসুমের লাশের খণ্ডিত অংশ ছাত্র-জনতার আন্দোলনের মুখে শেখ হাসিনা সরকারের পতনের পর রাজধানীসহ দেশের অধিকাংশ থানা ছেড়ে চলে গিয়েছিল পুলিশ। দেশের চার ব্যবসায়ী গ্রুপকে নিয়ম লঙ্ঘন করে বড় অঙ্কের সুদ মওকুফ সুবিধা দিয়েছে দুটি ব্যাংক। এস আলম                                                                                                                                                                                                                                                                                                     1
১৮ মার্চ ২০২৬ নব্বইয়ের দশকের জনপ্রিয় ক্রাইম থ্রিলার উপন্যাস সিরিজ ‘স্কারপেটা’ ফিরছে রুপালী পর্দায়। প্যাট্রিসিয়া কর্নওয়েলের কালজয়ী মেডিকেল এক্সামিনার চরিত্র কে স্কারপেটাকে কেন্দ্র করে নির্মিত নতুন ওয়েব বিখ্যাত ব্রিটিশ অভিনেতা স্যার প্যাট্রিক স্টুয়ার্ট উইলিয়াম শেকসপিয়রের সম্পূর্ণ সনেটগুচ্ছ নিয়ে একটি নতুন ‘অডিওবুক’ প্রকাশ করতে যাচ্ছেন। ‘সাইমন অ্যান্ড শুস্টার অডিও’ আগামী ৭ এপ্রিল বিশ্বজুড়ে এটি রুজভেল্ট দ্বীপে আবাস গাড়ার ক’দিন পরের কথা। হেমন্তের এক ভারি সুন্দর বিকেলে সবাই মিলে হাঁটতে বেরিয়েছি। বসেছি চারজনে ব্ল্যাকওয়ালদের বাড়ির সামনের রাস্তার উল্টোদিকের বেঞ্চিতে। হঠাৎ নিবিষ্ট কাতর যারা                                                                                                                                                                                1
১৮ মার্চ ২০২৬ মালয়েশিয়া যুক্তরাষ্ট্রের সঙ্গে স্বাক্ষরিত বাণিজ্য চুক্তি থেকে সরে দাঁড়িয়েছে। এর মাধ্যমে ওয়াশিংটনের ‘রিসিপ্রোকাল ট্যারিফ’ চুক্তি থেকে বেরিয়ে আসা প্রথম দেশ হিসেবে আত্মপ্রকাশ করল দেশটি। এ পদক্ষেপে অন্যান্য দেশও একই পথে হাঁটার সুযোগ পেতে পারে বলে ধারণা করা হচ্ছে রাজধানীর সদরঘাটে দুই লঞ্চের ধাক্কায় ইঞ্জিনচালিত নৌকার এক যাত্রী নিহত হয়েছেন। এ ঘটনায় দুইজন নিখোঁজ রয়েছেন। ‘কেডি-দ্য ডেভিল’ সিনেমার গানটি মুক্তির পর এর কথা ও নাচের ভঙ্গিমা জন্য আজ গানটি নিষেদ্ধ ঘোষণা করে ভারতের কেন্দ্রীয় সরকার। বিতর্কের মাঝে শুটিংসহ গানটির পেছনের গল্প জানিয়ে নিজের অবস্থান পরিস্কার করেছেন এই অভিনেত্রী।"                                                                                                                                                                              1
2026-03-18 23:37:11                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           1
2026-03-18 23:57:49                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           1
Name: count, dtype: int64

In [5]:
# Count category frequencies
category_counts = df["category"].value_counts()

# Keep only categories with more than 2 samples
valid_categories = category_counts[category_counts > 2].index

# Filter dataframe
df = df[df["category"].isin(valid_categories)]

# Optional: check result
print(df["category"].value_counts())

category
politics         3420
sports           2695
international    2300
national         1359
literature       1251
economy           861
economics         416
education          57
bangladesh         44
business           19
Name: count, dtype: int64

In [6]:
print(df["source"].value_counts())

source
gpt                    3681
claud                  2301
Samakal                1462
pdf                    1203
Prothom Alo            1141
Bangladesh Pratidin     943
Ittefaq                 820
Daily Star Bangla       463
Kalbela                 248
Dhaka Post              149
Jugantor                 11
Name: count, dtype: int64

In [7]:
print(df["class"].value_counts())

class
1    6440
0    5982
Name: count, dtype: int64

In [8]:
# checking for NaN value
df["category"].isna().sum()

np.int64(0)

In [11]:
# ---- Step 2: Create combined stratification column ----
df["stratify_col"] = df["source"].astype(str) + "_" + df["category"].astype(str)

# ---- Step 3: Remove rare combinations (important!) ----
combo_counts = df["stratify_col"].value_counts()
valid_combos = combo_counts[combo_counts > 1].index
df = df[df["stratify_col"].isin(valid_combos)]

# ---- Step 4: Stratified split ----
train_df, test_df = train_test_split(
    df,
    test_size=0.2,
    random_state=42,
    stratify=df["stratify_col"]
)

# ---- Optional: Drop helper column ----
train_df = train_df.drop(columns=["stratify_col"])
test_df = test_df.drop(columns=["stratify_col"])

# ---- Check distribution ----
print(train_df["category"].value_counts(normalize=True))
print(test_df["category"].value_counts(normalize=True))

category
politics         0.275463
sports           0.216888
international    0.184984
national         0.109400
literature       0.100644
economy          0.069444
economics        0.033514
education        0.004630
bangladesh       0.003523
business         0.001510
Name: proportion, dtype: float64
category
politics         0.274849
sports           0.217304
international    0.185513
national         0.109457
literature       0.101006
economy          0.068813
economics        0.033400
education        0.004427
bangladesh       0.003622
business         0.001610
Name: proportion, dtype: float64

In [12]:
print(test_df.columns)

Index(['source', 'category', 'data', 'class'], dtype='object')

In [13]:
# Keep only necessary columns
# train_df = train_df[["text", "label"]]
# test_df = test_df[["text", "label"]]

# Keep only necessary columns
train_df = train_df[["data", "class"]]
test_df = test_df[["data", "class"]]

train_df = train_df.rename(columns={"data": "text", "class": "label"})
test_df = test_df.rename(columns={"data": "text", "class": "label"})

### Convert to HuggingFace Dataset

In [14]:
train_dataset = Dataset.from_pandas(train_df.reset_index(drop=True))
test_dataset = Dataset.from_pandas(test_df.reset_index(drop=True))

### Load BanglaBert

In [15]:
model_name = "csebuetnlp/banglabert"

tokenizer = AutoTokenizer.from_pretrained(model_name)

config.json:   0%|          | 0.00/586 [00:00<?, ?B/s]

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

tokenizer_config.json:   0%|          | 0.00/119 [00:00<?, ?B/s]

vocab.txt: 0.00B [00:00, ?B/s]

special_tokens_map.json:   0%|          | 0.00/112 [00:00<?, ?B/s]

### Tokenization

In [16]:
def tokenize_function(example):
    return tokenizer(
        example["text"],
        padding="max_length",
        truncation=True,
        max_length=256
    )

train_dataset = train_dataset.map(tokenize_function, batched=True)
test_dataset = test_dataset.map(tokenize_function, batched=True)

Map:   0%|          | 0/9936 [00:00<?, ? examples/s]

Map:   0%|          | 0/2485 [00:00<?, ? examples/s]

### Set Format for PyTorch

In [19]:
train_dataset.set_format(type="torch", columns=["input_ids", "attention_mask", "label"])
test_dataset.set_format(type="torch", columns=["input_ids", "attention_mask", "label"])

### Load Model

In [20]:
model = AutoModelForSequenceClassification.from_pretrained(
    model_name,
    num_labels=2
)

pytorch_model.bin:   0%|          | 0.00/443M [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/443M [00:00<?, ?B/s]

Loading weights:   0%|          | 0/197 [00:00<?, ?it/s]

ElectraForSequenceClassification LOAD REPORT from: csebuetnlp/banglabert
Key                                               | Status     |
--------------------------------------------------+------------+-
discriminator_predictions.dense.bias              | UNEXPECTED |
discriminator_predictions.dense.weight            | UNEXPECTED |
discriminator_predictions.dense_prediction.bias   | UNEXPECTED |
discriminator_predictions.dense_prediction.weight | UNEXPECTED |
electra.embeddings.position_ids                   | UNEXPECTED |
classifier.dense.bias                             | MISSING    |
classifier.out_proj.bias                          | MISSING    |
classifier.dense.weight                           | MISSING    |
classifier.out_proj.weight                        | MISSING    |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING	:those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

### Define Evaluation Metrics

In [22]:
def compute_metrics(eval_pred):
    logits, labels = eval_pred
    preds = logits.argmax(axis=1)

    accuracy = accuracy_score(labels, preds)
    precision = precision_score(labels, preds)
    recall = recall_score(labels, preds)
    f1 = f1_score(labels, preds)

    return {
        "accuracy": accuracy,
        "precision": precision,
        "recall": recall,
        "f1": f1,
    }

### Training Arguments

In [23]:
training_args = TrainingArguments(
    output_dir="./results",
    eval_strategy="epoch",
    save_strategy="epoch",
    logging_dir="./logs",
    learning_rate=2e-5,
    per_device_train_batch_size=8,
    per_device_eval_batch_size=8,
    num_train_epochs=3,
    weight_decay=0.01,
    load_best_model_at_end=True,
)

`logging_dir` is deprecated and will be removed in v5.2. Please set `TENSORBOARD_LOGGING_DIR` instead.

### Trainer

In [27]:
data_collator = DataCollatorWithPadding(tokenizer=tokenizer)

trainer = Trainer(
    model=model,
    args=training_args,
    train_dataset=train_dataset,
    eval_dataset=test_dataset,
    data_collator=data_collator,
    compute_metrics=compute_metrics,
)

### Train

In [28]:
trainer.train()

/usr/local/lib/python3.12/dist-packages/torch/autograd/function.py:583: UserWarning: Was asked to gather along dimension 0, but all input tensors were scalars; will instead unsqueeze and return a vector.
  return super().apply(*args, **kwargs)  # type: ignore[misc]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

/usr/local/lib/python3.12/dist-packages/torch/autograd/function.py:583: UserWarning: Was asked to gather along dimension 0, but all input tensors were scalars; will instead unsqueeze and return a vector.
  return super().apply(*args, **kwargs)  # type: ignore[misc]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

/usr/local/lib/python3.12/dist-packages/torch/autograd/function.py:583: UserWarning: Was asked to gather along dimension 0, but all input tensors were scalars; will instead unsqueeze and return a vector.
  return super().apply(*args, **kwargs)  # type: ignore[misc]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

There were missing keys in the checkpoint model loaded: ['electra.embeddings.LayerNorm.weight', 'electra.embeddings.LayerNorm.bias', 'electra.encoder.layer.0.attention.output.LayerNorm.weight', 'electra.encoder.layer.0.attention.output.LayerNorm.bias', 'electra.encoder.layer.0.output.LayerNorm.weight', 'electra.encoder.layer.0.output.LayerNorm.bias', 'electra.encoder.layer.1.attention.output.LayerNorm.weight', 'electra.encoder.layer.1.attention.output.LayerNorm.bias', 'electra.encoder.layer.1.output.LayerNorm.weight', 'electra.encoder.layer.1.output.LayerNorm.bias', 'electra.encoder.layer.2.attention.output.LayerNorm.weight', 'electra.encoder.layer.2.attention.output.LayerNorm.bias', 'electra.encoder.layer.2.output.LayerNorm.weight', 'electra.encoder.layer.2.output.LayerNorm.bias', 'electra.encoder.layer.3.attention.output.LayerNorm.weight', 'electra.encoder.layer.3.attention.output.LayerNorm.bias', 'electra.encoder.layer.3.output.LayerNorm.weight', 'electra.encoder.layer.3.output.LayerNorm.bias', 'electra.encoder.layer.4.attention.output.LayerNorm.weight', 'electra.encoder.layer.4.attention.output.LayerNorm.bias', 'electra.encoder.layer.4.output.LayerNorm.weight', 'electra.encoder.layer.4.output.LayerNorm.bias', 'electra.encoder.layer.5.attention.output.LayerNorm.weight', 'electra.encoder.layer.5.attention.output.LayerNorm.bias', 'electra.encoder.layer.5.output.LayerNorm.weight', 'electra.encoder.layer.5.output.LayerNorm.bias', 'electra.encoder.layer.6.attention.output.LayerNorm.weight', 'electra.encoder.layer.6.attention.output.LayerNorm.bias', 'electra.encoder.layer.6.output.LayerNorm.weight', 'electra.encoder.layer.6.output.LayerNorm.bias', 'electra.encoder.layer.7.attention.output.LayerNorm.weight', 'electra.encoder.layer.7.attention.output.LayerNorm.bias', 'electra.encoder.layer.7.output.LayerNorm.weight', 'electra.encoder.layer.7.output.LayerNorm.bias', 'electra.encoder.layer.8.attention.output.LayerNorm.weight', 'electra.encoder.layer.8.attention.output.LayerNorm.bias', 'electra.encoder.layer.8.output.LayerNorm.weight', 'electra.encoder.layer.8.output.LayerNorm.bias', 'electra.encoder.layer.9.attention.output.LayerNorm.weight', 'electra.encoder.layer.9.attention.output.LayerNorm.bias', 'electra.encoder.layer.9.output.LayerNorm.weight', 'electra.encoder.layer.9.output.LayerNorm.bias', 'electra.encoder.layer.10.attention.output.LayerNorm.weight', 'electra.encoder.layer.10.attention.output.LayerNorm.bias', 'electra.encoder.layer.10.output.LayerNorm.weight', 'electra.encoder.layer.10.output.LayerNorm.bias', 'electra.encoder.layer.11.attention.output.LayerNorm.weight', 'electra.encoder.layer.11.attention.output.LayerNorm.bias', 'electra.encoder.layer.11.output.LayerNorm.weight', 'electra.encoder.layer.11.output.LayerNorm.bias'].
There were unexpected keys in the checkpoint model loaded: ['electra.embeddings.LayerNorm.beta', 'electra.embeddings.LayerNorm.gamma', 'electra.encoder.layer.0.attention.output.LayerNorm.beta', 'electra.encoder.layer.0.attention.output.LayerNorm.gamma', 'electra.encoder.layer.0.output.LayerNorm.beta', 'electra.encoder.layer.0.output.LayerNorm.gamma', 'electra.encoder.layer.1.attention.output.LayerNorm.beta', 'electra.encoder.layer.1.attention.output.LayerNorm.gamma', 'electra.encoder.layer.1.output.LayerNorm.beta', 'electra.encoder.layer.1.output.LayerNorm.gamma', 'electra.encoder.layer.2.attention.output.LayerNorm.beta', 'electra.encoder.layer.2.attention.output.LayerNorm.gamma', 'electra.encoder.layer.2.output.LayerNorm.beta', 'electra.encoder.layer.2.output.LayerNorm.gamma', 'electra.encoder.layer.3.attention.output.LayerNorm.beta', 'electra.encoder.layer.3.attention.output.LayerNorm.gamma', 'electra.encoder.layer.3.output.LayerNorm.beta', 'electra.encoder.layer.3.output.LayerNorm.gamma', 'electra.encoder.layer.4.attention.output.LayerNorm.beta', 'electra.encoder.layer.4.attention.output.LayerNorm.gamma', 'electra.encoder.layer.4.output.LayerNorm.beta', 'electra.encoder.layer.4.output.LayerNorm.gamma', 'electra.encoder.layer.5.attention.output.LayerNorm.beta', 'electra.encoder.layer.5.attention.output.LayerNorm.gamma', 'electra.encoder.layer.5.output.LayerNorm.beta', 'electra.encoder.layer.5.output.LayerNorm.gamma', 'electra.encoder.layer.6.attention.output.LayerNorm.beta', 'electra.encoder.layer.6.attention.output.LayerNorm.gamma', 'electra.encoder.layer.6.output.LayerNorm.beta', 'electra.encoder.layer.6.output.LayerNorm.gamma', 'electra.encoder.layer.7.attention.output.LayerNorm.beta', 'electra.encoder.layer.7.attention.output.LayerNorm.gamma', 'electra.encoder.layer.7.output.LayerNorm.beta', 'electra.encoder.layer.7.output.LayerNorm.gamma', 'electra.encoder.layer.8.attention.output.LayerNorm.beta', 'electra.encoder.layer.8.attention.output.LayerNorm.gamma', 'electra.encoder.layer.8.output.LayerNorm.beta', 'electra.encoder.layer.8.output.LayerNorm.gamma', 'electra.encoder.layer.9.attention.output.LayerNorm.beta', 'electra.encoder.layer.9.attention.output.LayerNorm.gamma', 'electra.encoder.layer.9.output.LayerNorm.beta', 'electra.encoder.layer.9.output.LayerNorm.gamma', 'electra.encoder.layer.10.attention.output.LayerNorm.beta', 'electra.encoder.layer.10.attention.output.LayerNorm.gamma', 'electra.encoder.layer.10.output.LayerNorm.beta', 'electra.encoder.layer.10.output.LayerNorm.gamma', 'electra.encoder.layer.11.attention.output.LayerNorm.beta', 'electra.encoder.layer.11.attention.output.LayerNorm.gamma', 'electra.encoder.layer.11.output.LayerNorm.beta', 'electra.encoder.layer.11.output.LayerNorm.gamma'].

TrainOutput(global_step=1863, training_loss=0.22203243437852516, metrics={'train_runtime': 990.2693, 'train_samples_per_second': 30.101, 'train_steps_per_second': 1.881, 'total_flos': 3921407169085440.0, 'train_loss': 0.22203243437852516, 'epoch': 3.0})

### Evaluate

In [29]:
results = trainer.evaluate()
print(results)

/usr/local/lib/python3.12/dist-packages/torch/autograd/function.py:583: UserWarning: Was asked to gather along dimension 0, but all input tensors were scalars; will instead unsqueeze and return a vector.
  return super().apply(*args, **kwargs)  # type: ignore[misc]

{'eval_loss': 0.21242353320121765, 'eval_accuracy': 0.9750503018108652, 'eval_precision': 0.9658314350797267, 'eval_recall': 0.9868114817688131, 'eval_f1': 0.9762087490406753, 'eval_runtime': 26.8088, 'eval_samples_per_second': 92.694, 'eval_steps_per_second': 5.819, 'epoch': 3.0}

### Predict

In [31]:
predictions = trainer.predict(test_dataset)
preds = predictions.predictions.argmax(axis=1)

test_df["predicted"] = preds

/usr/local/lib/python3.12/dist-packages/torch/autograd/function.py:583: UserWarning: Was asked to gather along dimension 0, but all input tensors were scalars; will instead unsqueeze and return a vector.
  return super().apply(*args, **kwargs)  # type: ignore[misc]

### K-fold validation

In [1]:
import pandas as pd
import torch
from sklearn.model_selection import StratifiedKFold
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score
from transformers import AutoTokenizer, AutoModelForSequenceClassification, Trainer, TrainingArguments, DataCollatorWithPadding 
from datasets import Dataset
import numpy as np

# Load dataset
df = pd.read_csv("/kaggle/input/datasets/nabilatabassummumu/our-dataset/merged_dataset.csv")

# Rename columns
df = df.rename(columns={"data": "text", "class": "label"})

# ---- Step 1: Remove rare categories ----
cat_counts = df["category"].value_counts()
df = df[df["category"].isin(cat_counts[cat_counts > 2].index)]

# ---- Step 2: Create combined stratification ----
df["stratify_col"] = df["source"].astype(str) + "_" + df["category"].astype(str) + "_" + df["label"].astype(str)

# ---- Step 3: Remove rare combinations ----
combo_counts = df["stratify_col"].value_counts()
df = df[df["stratify_col"].isin(combo_counts[combo_counts >= 5].index)]

# Load tokenizer
model_name = "csebuetnlp/banglabert"
tokenizer = AutoTokenizer.from_pretrained(model_name)

def tokenize_function(example):
    return tokenizer(example["text"], padding="max_length", truncation=True, max_length=256)

def compute_metrics(eval_pred):
    logits, labels = eval_pred
    preds = np.argmax(logits, axis=1)
    return {
        "accuracy": accuracy_score(labels, preds),
        "precision": precision_score(labels, preds),
        "recall": recall_score(labels, preds),
        "f1": f1_score(labels, preds),
    }

# Stratified K-Fold
skf = StratifiedKFold(n_splits=5, shuffle=True, random_state=42)

all_results = []

for fold, (train_idx, val_idx) in enumerate(skf.split(df["text"], df["label"])):
    print(f"\n===== Fold {fold+1} =====")

    train_df = df.iloc[train_idx][["text", "label"]]
    val_df = df.iloc[val_idx][["text", "label"]]
    
    train_dataset = Dataset.from_pandas(train_df.reset_index(drop=True))
    val_dataset = Dataset.from_pandas(val_df.reset_index(drop=True))

    train_dataset = train_dataset.map(tokenize_function, batched=True)
    val_dataset = val_dataset.map(tokenize_function, batched=True)

    train_dataset.set_format(type="torch", columns=["input_ids", "attention_mask", "label"])
    val_dataset.set_format(type="torch", columns=["input_ids", "attention_mask", "label"])

    model = AutoModelForSequenceClassification.from_pretrained(
        model_name,
        num_labels=2
    )

    training_args = TrainingArguments(
        output_dir=f"./results_fold_{fold}",
        eval_strategy="epoch",
        save_strategy="no",
        logging_strategy="epoch",
        learning_rate=2e-5,
        per_device_train_batch_size=8,
        per_device_eval_batch_size=8,
        num_train_epochs=3,
        weight_decay=0.01,
        disable_tqdm=False
    )

    data_collator = DataCollatorWithPadding(tokenizer=tokenizer)

    trainer = Trainer(
        model=model,
        args=training_args,
        train_dataset=train_dataset,
        eval_dataset=val_dataset,
        data_collator=data_collator,
        compute_metrics=compute_metrics,
    )

    trainer.train()
    results = trainer.evaluate()

    print(results)
    all_results.append(results)

# Average results
avg_results = {
    metric: np.mean([fold_result[f"eval_{metric}"] for fold_result in all_results])
    for metric in ["accuracy", "precision", "recall", "f1"]
}

print("\n===== Final Averaged Results =====")
print(avg_results)

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

config.json:   0%|          | 0.00/586 [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/119 [00:00<?, ?B/s]

vocab.txt: 0.00B [00:00, ?B/s]

special_tokens_map.json:   0%|          | 0.00/112 [00:00<?, ?B/s]

===== Fold 1 =====

Map:   0%|          | 0/9935 [00:00<?, ? examples/s]

Map:   0%|          | 0/2484 [00:00<?, ? examples/s]

pytorch_model.bin:   0%|          | 0.00/443M [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/443M [00:00<?, ?B/s]

Loading weights:   0%|          | 0/197 [00:00<?, ?it/s]

ElectraForSequenceClassification LOAD REPORT from: csebuetnlp/banglabert
Key                                               | Status     |
--------------------------------------------------+------------+-
electra.embeddings.position_ids                   | UNEXPECTED |
discriminator_predictions.dense.weight            | UNEXPECTED |
discriminator_predictions.dense_prediction.bias   | UNEXPECTED |
discriminator_predictions.dense.bias              | UNEXPECTED |
discriminator_predictions.dense_prediction.weight | UNEXPECTED |
classifier.out_proj.bias                          | MISSING    |
classifier.dense.bias                             | MISSING    |
classifier.out_proj.weight                        | MISSING    |
classifier.dense.weight                           | MISSING    |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING	:those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.
/usr/local/lib/python3.12/dist-packages/torch/autograd/function.py:583: UserWarning: Was asked to gather along dimension 0, but all input tensors were scalars; will instead unsqueeze and return a vector.
  return super().apply(*args, **kwargs)  # type: ignore[misc]

/usr/local/lib/python3.12/dist-packages/torch/autograd/function.py:583: UserWarning: Was asked to gather along dimension 0, but all input tensors were scalars; will instead unsqueeze and return a vector.
  return super().apply(*args, **kwargs)  # type: ignore[misc]
/usr/local/lib/python3.12/dist-packages/torch/autograd/function.py:583: UserWarning: Was asked to gather along dimension 0, but all input tensors were scalars; will instead unsqueeze and return a vector.
  return super().apply(*args, **kwargs)  # type: ignore[misc]
/usr/local/lib/python3.12/dist-packages/torch/autograd/function.py:583: UserWarning: Was asked to gather along dimension 0, but all input tensors were scalars; will instead unsqueeze and return a vector.
  return super().apply(*args, **kwargs)  # type: ignore[misc]

{'eval_loss': 0.23587016761302948, 'eval_accuracy': 0.9790660225442834, 'eval_precision': 0.9873717442778216, 'eval_recall': 0.972027972027972, 'eval_f1': 0.9796397807361003, 'eval_runtime': 27.0836, 'eval_samples_per_second': 91.716, 'eval_steps_per_second': 5.76, 'epoch': 3.0}

===== Fold 2 =====

Map:   0%|          | 0/9935 [00:00<?, ? examples/s]

Map:   0%|          | 0/2484 [00:00<?, ? examples/s]

Loading weights:   0%|          | 0/197 [00:00<?, ?it/s]

ElectraForSequenceClassification LOAD REPORT from: csebuetnlp/banglabert
Key                                               | Status     |
--------------------------------------------------+------------+-
electra.embeddings.position_ids                   | UNEXPECTED |
discriminator_predictions.dense.weight            | UNEXPECTED |
discriminator_predictions.dense_prediction.bias   | UNEXPECTED |
discriminator_predictions.dense.bias              | UNEXPECTED |
discriminator_predictions.dense_prediction.weight | UNEXPECTED |
classifier.out_proj.bias                          | MISSING    |
classifier.dense.bias                             | MISSING    |
classifier.out_proj.weight                        | MISSING    |
classifier.dense.weight                           | MISSING    |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING	:those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.
/usr/local/lib/python3.12/dist-packages/torch/autograd/function.py:583: UserWarning: Was asked to gather along dimension 0, but all input tensors were scalars; will instead unsqueeze and return a vector.
  return super().apply(*args, **kwargs)  # type: ignore[misc]

/usr/local/lib/python3.12/dist-packages/torch/autograd/function.py:583: UserWarning: Was asked to gather along dimension 0, but all input tensors were scalars; will instead unsqueeze and return a vector.
  return super().apply(*args, **kwargs)  # type: ignore[misc]
/usr/local/lib/python3.12/dist-packages/torch/autograd/function.py:583: UserWarning: Was asked to gather along dimension 0, but all input tensors were scalars; will instead unsqueeze and return a vector.
  return super().apply(*args, **kwargs)  # type: ignore[misc]
/usr/local/lib/python3.12/dist-packages/torch/autograd/function.py:583: UserWarning: Was asked to gather along dimension 0, but all input tensors were scalars; will instead unsqueeze and return a vector.
  return super().apply(*args, **kwargs)  # type: ignore[misc]

{'eval_loss': 0.2797299027442932, 'eval_accuracy': 0.9742351046698873, 'eval_precision': 0.9803613511390417, 'eval_recall': 0.9696969696969697, 'eval_f1': 0.975, 'eval_runtime': 27.06, 'eval_samples_per_second': 91.796, 'eval_steps_per_second': 5.765, 'epoch': 3.0}

===== Fold 3 =====

Map:   0%|          | 0/9935 [00:00<?, ? examples/s]

Map:   0%|          | 0/2484 [00:00<?, ? examples/s]

Loading weights:   0%|          | 0/197 [00:00<?, ?it/s]

ElectraForSequenceClassification LOAD REPORT from: csebuetnlp/banglabert
Key                                               | Status     |
--------------------------------------------------+------------+-
electra.embeddings.position_ids                   | UNEXPECTED |
discriminator_predictions.dense.weight            | UNEXPECTED |
discriminator_predictions.dense_prediction.bias   | UNEXPECTED |
discriminator_predictions.dense.bias              | UNEXPECTED |
discriminator_predictions.dense_prediction.weight | UNEXPECTED |
classifier.out_proj.bias                          | MISSING    |
classifier.dense.bias                             | MISSING    |
classifier.out_proj.weight                        | MISSING    |
classifier.dense.weight                           | MISSING    |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING	:those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.
/usr/local/lib/python3.12/dist-packages/torch/autograd/function.py:583: UserWarning: Was asked to gather along dimension 0, but all input tensors were scalars; will instead unsqueeze and return a vector.
  return super().apply(*args, **kwargs)  # type: ignore[misc]

/usr/local/lib/python3.12/dist-packages/torch/autograd/function.py:583: UserWarning: Was asked to gather along dimension 0, but all input tensors were scalars; will instead unsqueeze and return a vector.
  return super().apply(*args, **kwargs)  # type: ignore[misc]
/usr/local/lib/python3.12/dist-packages/torch/autograd/function.py:583: UserWarning: Was asked to gather along dimension 0, but all input tensors were scalars; will instead unsqueeze and return a vector.
  return super().apply(*args, **kwargs)  # type: ignore[misc]
/usr/local/lib/python3.12/dist-packages/torch/autograd/function.py:583: UserWarning: Was asked to gather along dimension 0, but all input tensors were scalars; will instead unsqueeze and return a vector.
  return super().apply(*args, **kwargs)  # type: ignore[misc]

{'eval_loss': 0.28241270780563354, 'eval_accuracy': 0.9734299516908212, 'eval_precision': 0.9818611987381703, 'eval_recall': 0.9666149068322981, 'eval_f1': 0.9741784037558685, 'eval_runtime': 27.2889, 'eval_samples_per_second': 91.026, 'eval_steps_per_second': 5.717, 'epoch': 3.0}

===== Fold 4 =====

Map:   0%|          | 0/9935 [00:00<?, ? examples/s]

Map:   0%|          | 0/2484 [00:00<?, ? examples/s]

Loading weights:   0%|          | 0/197 [00:00<?, ?it/s]

ElectraForSequenceClassification LOAD REPORT from: csebuetnlp/banglabert
Key                                               | Status     |
--------------------------------------------------+------------+-
electra.embeddings.position_ids                   | UNEXPECTED |
discriminator_predictions.dense.weight            | UNEXPECTED |
discriminator_predictions.dense_prediction.bias   | UNEXPECTED |
discriminator_predictions.dense.bias              | UNEXPECTED |
discriminator_predictions.dense_prediction.weight | UNEXPECTED |
classifier.out_proj.bias                          | MISSING    |
classifier.dense.bias                             | MISSING    |
classifier.out_proj.weight                        | MISSING    |
classifier.dense.weight                           | MISSING    |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING	:those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.
/usr/local/lib/python3.12/dist-packages/torch/autograd/function.py:583: UserWarning: Was asked to gather along dimension 0, but all input tensors were scalars; will instead unsqueeze and return a vector.
  return super().apply(*args, **kwargs)  # type: ignore[misc]

/usr/local/lib/python3.12/dist-packages/torch/autograd/function.py:583: UserWarning: Was asked to gather along dimension 0, but all input tensors were scalars; will instead unsqueeze and return a vector.
  return super().apply(*args, **kwargs)  # type: ignore[misc]
/usr/local/lib/python3.12/dist-packages/torch/autograd/function.py:583: UserWarning: Was asked to gather along dimension 0, but all input tensors were scalars; will instead unsqueeze and return a vector.
  return super().apply(*args, **kwargs)  # type: ignore[misc]
/usr/local/lib/python3.12/dist-packages/torch/autograd/function.py:583: UserWarning: Was asked to gather along dimension 0, but all input tensors were scalars; will instead unsqueeze and return a vector.
  return super().apply(*args, **kwargs)  # type: ignore[misc]

{'eval_loss': 0.19455358386039734, 'eval_accuracy': 0.9818840579710145, 'eval_precision': 0.9836575875486381, 'eval_recall': 0.9813664596273292, 'eval_f1': 0.982510687912942, 'eval_runtime': 27.284, 'eval_samples_per_second': 91.042, 'eval_steps_per_second': 5.718, 'epoch': 3.0}

===== Fold 5 =====

Map:   0%|          | 0/9936 [00:00<?, ? examples/s]

Map:   0%|          | 0/2483 [00:00<?, ? examples/s]

Loading weights:   0%|          | 0/197 [00:00<?, ?it/s]

ElectraForSequenceClassification LOAD REPORT from: csebuetnlp/banglabert
Key                                               | Status     |
--------------------------------------------------+------------+-
electra.embeddings.position_ids                   | UNEXPECTED |
discriminator_predictions.dense.weight            | UNEXPECTED |
discriminator_predictions.dense_prediction.bias   | UNEXPECTED |
discriminator_predictions.dense.bias              | UNEXPECTED |
discriminator_predictions.dense_prediction.weight | UNEXPECTED |
classifier.out_proj.bias                          | MISSING    |
classifier.dense.bias                             | MISSING    |
classifier.out_proj.weight                        | MISSING    |
classifier.dense.weight                           | MISSING    |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING	:those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.
/usr/local/lib/python3.12/dist-packages/torch/autograd/function.py:583: UserWarning: Was asked to gather along dimension 0, but all input tensors were scalars; will instead unsqueeze and return a vector.
  return super().apply(*args, **kwargs)  # type: ignore[misc]

/usr/local/lib/python3.12/dist-packages/torch/autograd/function.py:583: UserWarning: Was asked to gather along dimension 0, but all input tensors were scalars; will instead unsqueeze and return a vector.
  return super().apply(*args, **kwargs)  # type: ignore[misc]
/usr/local/lib/python3.12/dist-packages/torch/autograd/function.py:583: UserWarning: Was asked to gather along dimension 0, but all input tensors were scalars; will instead unsqueeze and return a vector.
  return super().apply(*args, **kwargs)  # type: ignore[misc]
/usr/local/lib/python3.12/dist-packages/torch/autograd/function.py:583: UserWarning: Was asked to gather along dimension 0, but all input tensors were scalars; will instead unsqueeze and return a vector.
  return super().apply(*args, **kwargs)  # type: ignore[misc]

{'eval_loss': 0.15922942757606506, 'eval_accuracy': 0.9846959323399114, 'eval_precision': 0.9875097580015613, 'eval_recall': 0.9829059829059829, 'eval_f1': 0.985202492211838, 'eval_runtime': 27.4354, 'eval_samples_per_second': 90.503, 'eval_steps_per_second': 5.686, 'epoch': 3.0}

===== Final Averaged Results =====
{'accuracy': np.float64(0.9786622138431836), 'precision': np.float64(0.9841523279410467), 'recall': np.float64(0.9745224582181103), 'f1': np.float64(0.9793062729233497)}